server:
    http_listen_port: 3200

distributor:
    receivers:
        zipkin: #Se envian los datos desde zipkin a tempo

storage:
    trace:
        backend: local
        local:
            path: /tmp/tempo/blocks #ruta de guardado en un stories local (podriamos definir aqui la conexion con DB)
